language: java
jdk:
  - oraclejdk7
  - oraclejdk6
  - openjdk7
  - openjdk6
install: 
  - mvn -f uce/pom.xml clean install -DskipTests=true
script:
 - mvn -f uce/pom.xml test
after_success:
 - mvn -f uce/pom.xml checkstyle:checkstyle findbugs:findbugs
